export const ACTION_TYPES = /** @type {const} */ ({
  START_SESSION: 'START_SESSION',
  NAVIGATE: 'NAVIGATE',
  UPDATE_ANNOTATION: 'UPDATE_ANNOTATION',
  MARK_SAVED: 'MARK_SAVED',
  COMPLETE: 'COMPLETE',
  RESET: 'RESET',
});
